{% set name = "qurro" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c839ef124c695c19b338e31a959905fb59118e9deb47bb5dd596683f983eea2

build:
  number: 1
  entry_points:
    - qurro=qurro.scripts._plot:plot
    - q2-qurro=qurro.q2.plugin_setup:plugin
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - cython
    - numpy >=1.12.0
  run:
    - python >=3.7
    - altair >=4.0
    - biom-format >=2.1.9
    - h5py
    - click
    - scipy >=1.3.0
    - pandas >=1
    - scikit-bio >0.5.3

test:
  imports:
    - qurro
  commands:
    - qurro --help

about:
  home: https://github.com/biocore/qurro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Visualizes 'omic feature rankings and log ratios
  description: |
    Qurro generates interactive visualizations of feature rankings (defined
    as some sortable measure of feature-wise variation, for example estimated
    log-fold changes or the feature loadings in a biplot) alongside a plot of
    selected features' log-ratios across samples in a dataset. The
    visualization contains various controls to support exploration of
    log-ratios of features using the feature rankings as a starting point.

extra:
  recipe-maintainers:
    - fedarko
