{% set name = "qurro" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6168772a8351ad9fa0c60931684dd75d459e58c7135d51012f3b85ce043a8833

build:
  number: 1
  entry_points:
    - qurro=qurro.scripts._plot:plot
    - q2-qurro=qurro.q2.plugin_setup:plugin
  skip: true  # [py<35 or py>37 or win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy >=1.12.0
  run:
    - python
    - altair =3.1.0
    - biom-format
    - h5py
    - click
    - {{ pin_compatible('numpy') }}
    - pandas >=0.20.1,<1
    - scikit-bio >0.5.3

test:
  imports:
    - qurro
  commands:
    - qurro --help

about:
  home: https://github.com/biocore/qurro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Visualizes 'omic feature rankings and log ratios
  description: |
    Qurro generates interactive visualizations of feature rankings (defined
    as some sortable measure of feature-wise variation, for example estimated
    log-fold changes or the feature loadings in a biplot) alongside a plot of
    selected features' log-ratios across samples in a dataset. The
    visualization contains various controls to support exploration of
    log-ratios of features using the feature rankings as a starting point.

extra:
  recipe-maintainers:
    - fedarko
