{% set name = "qurro" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8c9ef36de770c4a1668fc6baf8e40aaa64700772330012421d3193e8d2af287

build:
  number: 0
  entry_points:
    - qurro=qurro.scripts._plot:plot
    - q2-qurro=qurro.q2.plugin_setup:plugin
  skip: true  # [py<36 or py>=310 or win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy >=1.12.0
  run:
    - python
    - altair =3.1.0
    - biom-format >=2.1.9
    - h5py
    - click
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3.0,<1.9.0
    - pandas >=1
    - scikit-bio >0.5.3

test:
  imports:
    - qurro
  commands:
    - qurro --help

about:
  home: https://github.com/biocore/qurro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Visualizes 'omic feature rankings and log ratios
  description: |
    Qurro generates interactive visualizations of feature rankings (defined
    as some sortable measure of feature-wise variation, for example estimated
    log-fold changes or the feature loadings in a biplot) alongside a plot of
    selected features' log-ratios across samples in a dataset. The
    visualization contains various controls to support exploration of
    log-ratios of features using the feature rankings as a starting point.

extra:
  recipe-maintainers:
    - fedarko
